config/routes.rb
WonderlandStore::Application.routes.draw do
  
  root :to => "store#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :store
  match "index" => "store#index", :via => :get, :as => "index"
  
  match "about" => "store#about", :via => :get, :as => "about"
  
  match "contact" => "store#contact", :via => :get, :as => "contact"
  
  match "admin" => "store#admin", :via => :get, :as => "admin"
  
  match "sale" => "store#sale", :via => :get, :as => "sale"
  
  match "new" => "store#new", :via => :get, :as => "new"
  
  match "all" => "store#all", :via => :get, :as => "all"
  
  match "updated" => "store#updated", :via => :get, :as => "updated"
  
  match "check_out" => "store#check_out", :via => :get, :as => "check_out"
  
  match "customer_info" => "store#customer_info", :via => :get, :as => "customer_info"
  
  match "add_order" => "store#add_order", :via => :get, :as => "add_order"
  
  match "customers" => "store#customers", :via => :post, :as => "customers"
  
  match "product/:id" => "store#product", :via => :get, :as => "product"
  
  match "category/:id" => "store#category", :via => :get, :as => "category"
  
  match "add_product/:id" => "store#add_product", :via => :get, :as => "add_product"
        
  match "remove_product/:id" => "store#remove_product", :via => :get, :as => "remove_product"
  
  match "clear_products" => "store#clear_products", :via => :get, :as => "clear_products"
  
  match "search_results" => "store#search_results", :via => :post, :as => 'search_results'

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @featured = Product.where(:featured => true)
    @new_products = Product.order(:created_at).limit(3)
    @updated_products = Product.order(:updated_at).limit(3)
  end
  
  def category
    @category_products = Category.find(params[:id]).products
  end
  
  def product
    @product = Product.find(params[:id])
  end
  
  def contact
    @contact = Page.where("name = 'Contact'")
  end
  
  def about
    @about = Page.where("name = 'About'")
  end
  
  def sale
    @sale_products = Product.where("sale_price IS NOT NULL").where("sale_price != 0.0")
  end
  
  def new
    @new_products = Product.order(:created_at)
  end
  
  def updated
    @updated_products = Product.order(:updated_at)
  end
  
  def all
    @all_products = Product.order(:category_id)
  end
  
  def check_out
    @customer = Customer.find(session[:customer][0])
    @total = session[:total][0]
    @grand_total = 0.0
  end
  
  def customer_info
    @customer = Customer.new
    @provinces = Province.order(:name)
  end
  
  def add_order
    customer = Customer.find(session[:customer][0])
    product = customer.province
    order = Order.new( :customer_id => customer.id,
                        :gst_rate => product.gst,
                        :pst_rate => product.pst, 
                        :hst_rate => product.hst
                      )
    
    if (order.save)
      
      @my_products.each do |my_product|
        price = my_product[:product].price - my_product[:product].sale_price
        order_product = OrderProduct.new(:order_id => order.id,
                                          :product_id => my_product[:product].id,
                                          :price => price,
                                          :quantity => my_product[:quantity]
                                          )
        order_product.save
      end
      
      flash[:custom] = "Order completed successfully." 
    else
      flash[:custom] = "Order Could Not Be processed."
    end
    
    session[:products] = nil
    session[:quantity] = nil
    
    redirect_to root_url
  end
  
  def customers
    @customer = Customer.new(params[:customer])
    @customer.save

    if session[:customer][0].nil?
      session[:customer][0] << @customer.id
    else
      session[:customer][0] = @customer.id
    end

    redirect_to check_out_path
  end
  
  def search_results
    keywords = params[:keywords]
    
    @product = Product.where("name LIKE ? OR description LIKE ?", "%#{keywords}%", "%#{keywords}%")
    
    if @product.empty? 
      flash[:custom] = "No results found for #{params[:keywords]}" 
      redirect_to root_url
    end

  end
  
  def add_product
      if session[:products].include?(params[:id])
        index = session[:products].index("#{params[:id]}")
        session[:quantity][index] += 1
      else
        session[:products] << params[:id]
        session[:quantity] << 1
      end
      
      if Product.find(params[:id]).sale_price == 0.0
        price = Product.find(params[:id]).price        
      else
        price = Product.find(params[:id]).sale_price
      end
         
      session[:total][0] += price
      
      redirect_to :back      
  end
  
  def remove_product
    index = session[:products].index("#{params[:id]}")
    if session[:quantity][index] > 1
      session[:quantity][index] -= 1
    else
    session[:quantity].delete(index)
    session[:products].delete(params[:id])
    end
    
    if Product.find(params[:id]).sale_price == 0.0
      price = Product.find(params[:id]).price        
    else
      price = Product.find(params[:id]).sale_price
    end
    
    session[:total][0] -= price
    
    redirect_to :back
  end
  
  def clear_products
    session[:products] = nil
    session[:quantity] = nil
    session[:total][0] = 0.0

    redirect_to :back
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/_product.html.erb
  <div class="product" >
    <%= link_to (product_path(product.id)) do %>

      <h4><%= product.name %></h4>
      
      <% if product.image.nil? || product.image.strip == "" %>
        <%= image_tag "imageNotAvailable.png" %> 
      <% else %>
        <%= image_tag "#{product.image}" %>      
      <% end %>
      
      <% if product.sale_price.nil? || product.sale_price == 0.0 %>
        <p><%= product.price %></p>
      <% else %>
        <p class="cross_out" ><%= product.price %></p>
        <p class="sale_price" ><%= product.sale_price %></p>
      <% end %>
    <% end %>
  
    <%= render :partial => 'productLinks', :locals => { :cart => false, :product => product } %>
    
    <% if show_description %>
      <p><%= product.description %></p>
    <% end %>
  </div>

app/views/store/_productLinks.html.erb
<% if cart %>
  <%= link_to 'Remove', remove_product_path(product) %>
<% else %>
  <%= link_to 'Add to Cart', add_product_path(product) %>
<% end %>

app/views/store/about.html.erb
<p>
  <%= @about[0].content %>
</p>

app/views/store/all.html.erb
<% @all_products.each do |product| %>
  <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
<% end %>

app/views/store/category.html.erb
<% @category_products.each do |product| %>
  <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
<% end %>

app/views/store/check_out.html.erb
<div id="invoice">
  <% if @my_products.empty? %>
    <p>You have no items in your shopping cart</p>
  <% else %>
    <% @my_products.each do |my_product| %>
      <%= my_product[:quantity] %> x
      <%= my_product[:product].name %> ---
      $<%= my_product[:product].price %> . . . . . . . . . . . . . . . <%= number_to_currency(my_product[:product].price * my_product[:quantity]) %>
        <%= render :partial => 'productLinks', :locals => { :cart => false, :product => my_product[:product]} %>
        <%= render :partial => 'productLinks', :locals => { :cart => true, :product => my_product[:product]} %>
      <br />
    <% end %>
    <div id="totals">
      <p>Sub-Total: <%= number_to_currency(@total) %>
      <% @grand_total += (@total) %>
      <% if @customer.province.gst != 0.0 && @customer.province.gst != nil %>
        <br />GST: . . . . . . .<%= number_to_currency(@total * @customer.province.gst) %>
        <% @grand_total += (@total * @customer.province.gst) %>
      <% end %>
      
      <% if @customer.province.pst != 0.0 && @customer.province.pst != nil %>
        <br />PST: . . . . . . .<%= number_to_currency(@total * @customer.province.pst) %>
        <% @grand_total += (@total * @customer.province.pst) %>
      <% end %>
      
      <% if @customer.province.hst != 0.0 && @customer.province.hst != nil %>
        <br />HST: . . . . . . .<%= number_to_currency(@total * @customer.province.hst) %>
        <% @grand_total += (@total * @customer.province.hst) %>
      <% end %>
      
      <br />Grand Total: <%= number_to_currency(@grand_total) %>
      </p>
    </div>

  <% end %>
  
  <hr />
  
  <p>
    <%= @customer.name %>
      <br />
    <%= @customer.email %>
      <br />
    <%= @customer.street_address %>, <%= @customer.city %>
      <br />
    <%= @customer.postal_code %>
      <br />
    <%= @customer.province.name %> <%= @customer.country %>
  </p>
  
  <% if not @my_products.empty? %>
    <%= link_to 'Confirm Order', add_order_path %>
  <% end %>
</div>




app/views/store/contact.html.erb
<p>
  <%= @contact[0].content %>
</p>

app/views/store/customer_info.html.erb
<%= form_for(@customer) do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br />
    
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br />

    <%= f.label :street_address %>
    <%= f.text_field :street_address %><br />

    <%= f.label :city %>
    <%= f.text_field :city %><br />
    
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %><br />   
    
    <%= f.label :province_id %>
    <%= f.collection_select :province_id, @provinces, :id, :name %><br />   
    
    <%= f.label :country %>
    <%= f.country_select :country, nil, :required => true %>  <br />   
    
    <%= f.label :email %>
    <%= f.text_field :email %><br />

    <%= f.submit %>

<% end %>

app/views/store/index.html.erb
  <div id="featured">
    <%= link_to (product_path(@featured[0].id)) do %>
      <%= image_tag "#{@featured[0].image}" %>
      <h3 id="name"><%= @featured[0].name %></h3>
    <% end %>
  </div>

<hr />

  <div id="new">
    <%= link_to 'See More ...', new_path %>
    <% @new_products.each do |product| %>
      <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
    <% end %>
  </div>

<hr />

  <div id="updated">
    <%= link_to 'See More ...', updated_path %>
    <% @updated_products.each do |product| %>
      <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
    <% end %>
  </div>

app/views/store/new.html.erb
<% @new_products.each do |product| %>
  <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
<% end %>

app/views/store/product.html.erb
<%= render :partial => "product", :object => @product, :locals => { :show_description  => true} %>

app/views/store/sale.html.erb
<% @sale_products.each do |product| %>
  <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
<% end %>

app/views/store/search_results.html.erb
<% @product.each do |product| %>
  <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
<% end %>

app/views/store/updated.html.erb
<% @updated_products.each do |product| %>
  <%= render :partial => "product", :object => product, :locals => { :show_description => false } %>
<% end %>