config/routes.rb
WonderlandStore::Application.routes.draw do
  
  root :to => "store#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :store
  match "index" => "store#index", :via => :get, :as => "index"
  
  match "about" => "store#about", :via => :get, :as => "about"
  
  match "contact" => "store#contact", :via => :get, :as => "contact"
  
  match "admin" => "store#admin", :via => :get, :as => "admin"
  
  match "sale" => "store#sale", :via => :get, :as => "sale"
  
  match "new" => "store#new", :via => :get, :as => "new"
  
  match "all" => "store#all", :via => :get, :as => "all"
  
  match "updated" => "store#updated", :via => :get, :as => "updated"
  
  match "check_out" => "store#check_out", :via => :get, :as => "check_out"
  
  match "customer_info" => "store#customer_info", :via => :get, :as => "customer_info"
  
  match "add_order" => "store#add_order", :via => :get, :as => "add_order"
  
  match "customers" => "store#customers", :via => :post, :as => "customers"
  
  match "product/:id" => "store#product", :via => :get, :as => "product"
  
  match "category/:id" => "store#category", :via => :get, :as => "category"
  
  match "add_product/:id" => "store#add_product", :via => :get, :as => "add_product"
        
  match "remove_product/:id" => "store#remove_product", :via => :get, :as => "remove_product"
  
  match "clear_products" => "store#clear_products", :via => :get, :as => "clear_products"
  
  match "search_results" => "store#search_results", :via => :post, :as => 'search_results'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wonderland Store</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= link_to(image_tag("LOGO.png"), index_path ) %>
      <div id="topNav" >
        <nav>
          <ul>
            <li><%= link_to 'Home', index_path %></li>
            <li><%= link_to 'Sale Items', sale_path %></li>
            <li><%= link_to 'New Items', new_path %></li>
            <li><%= link_to 'Recently Updated Items', updated_path %></li>
          </ul>
        </nav>
      </div>
      <div id="search">
        <%= form_tag(search_results_path) do %>
          <%= label_tag(:keywords, "Search:") %>
          <%= text_field_tag(:keywords) %>
          <%= submit_tag("Search") %>
        <% end %>
        <%= flash[:custom] %>
      </div>
      <%= link_to 'Admin', admin_path %>
    </header>
    
  <hr />
    
    <aside>
      <div id="shopping_cart">
        <h5>Shopping Cart</h5>
        <% if @my_products.empty? %>
          <p>You have no items in your shopping cart</p>
        <% else %>
          <% @my_products.each do |my_product| %>
            <p>
              <%= my_product[:quantity] %> x
              <%= my_product[:product].name %> ---
              <%= my_product[:product].price %>
              <%= render :partial => 'productLinks', :locals => { :cart => true, :product => my_product[:product]} %>
            </p>
          <% end %>
            <%= link_to 'Clear Cart', clear_products_path %>
            <%= link_to 'Proceed to Check Out', customer_info_path %>
        <% end %>
      </div>
      
      <div id="categories">
        <h5>Categories</h5>
        <%= link_to "All Categories", all_path %>
        <ul>
          <% @all_categories.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category.id) %></li>
          <% end %>
        </ul>
      </div>
    </aside>
    
    <section>
      <%= yield %>
    </section>      
  
  <hr />
  
    <footer>
      <div id="bottomNav" >
        <nav>
          <ul>
            <li><%= link_to 'Home', index_path %></li>        
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
          </ul>
        </nav>
      </div>
    </footer>       
  </body>
</html>